"""
╔══════════════════════════════════════════════════════════════════╗
║         CLINIC APPOINTMENT CHATBOT  —  Flask Backend            ║
║         Reusable · Multi-client · International-ready           ║
╠══════════════════════════════════════════════════════════════════╣
║  HOW TO CUSTOMISE FOR A NEW CLIENT:                             ║
║    1.  Edit CLINIC_CONFIG below — nothing else needs changing.  ║
║    2.  Fill in telegram_bot_token / telegram_chat_id in CLINICS.║
║    3.  To reset appointment data: delete appointments.db        ║
║        — it is recreated automatically on next startup.         ║
║                                                                 ║
║  MULTI-CLIENT SAFETY:                                           ║
║    Keep each client in a separate project folder.               ║
║    Never share the same appointments.db across clients.         ║
╚══════════════════════════════════════════════════════════════════╝
"""

from flask import Flask, request, jsonify, render_template, redirect, url_for
import json, os, sqlite3
from datetime import datetime, date, timedelta
import requests   # pip install requests

# ══════════════════════════════════════════════════════════════════
#  CLINIC CONFIGURATION  ←  Edit this section only
# ══════════════════════════════════════════════════════════════════
CLINIC_CONFIG = {
    # Identity
    "clinic_name":            "CarePlus Clinic",
    "clinic_tagline":         "Trusted care, every visit",

    # Contact & location
    "clinic_location":        "London, UK",

    # Hours — used to auto-generate time slots
    # Format: "H:MM AM – H:MM PM"  or  "H AM – H PM"
    "clinic_timings":         "9:00 AM – 6:00 PM",
    "clinic_days":            "Monday to Saturday",

    # Fees (shown exactly as written — supports any currency)
    "clinic_fees":            "$20",

    # UI theme (any valid CSS colour)
    "primary_color":          "#2563eb",

    # Slot control — max appointments per calendar day
    # Time slots are auto-generated by dividing clinic hours by this number
    "daily_slot_limit":       10,

    # Hidden admin path — change this, share only with clinic owner
    "admin_path":             "admin-unique123",

    # Your deployed domain (no trailing slash)
    # Local:      http://localhost:5000
    # Production: https://yourclinic.com
    "site_url":               "http://localhost:5000",
}

# ── Base URL for building dashboard links in notifications ────────
# Set BASE_URL env var to your public domain, e.g. https://yourclinic.com
# Falls back to CLINIC_CONFIG site_url for local testing.
BASE_URL = os.environ.get("BASE_URL", "").rstrip("/")

# ══════════════════════════════════════════════════════════════════
#  MULTI-CLINIC REGISTRY
#  Add one entry per clinic. clinic_id must match the ?clinic= param
#  in booking links.
#
#  Each clinic has its own Telegram bot + chat_id for notifications.
#  Get these from @BotFather on Telegram.
# ══════════════════════════════════════════════════════════════════
CLINICS = {
    "clinic1": {
        "name":                "ABC Clinic",
        "telegram_bot_token":  os.getenv("TELEGRAM_BOT_TOKEN", "PASTE_BOT_TOKEN_HERE"),
        "telegram_chat_id":    os.getenv("TELEGRAM_CHAT_ID",   "PASTE_CHAT_ID_HERE"),
        "dashboard":           "/admin-clinic1",
    },
    # Add more clinics here following the same pattern:
    # "clinic2": {
    #     "name":               "XYZ Clinic",
    #     "telegram_bot_token": os.getenv("TELEGRAM_BOT_TOKEN_2"),
    #     "telegram_chat_id":   os.getenv("TELEGRAM_CHAT_ID_2"),
    #     "dashboard":          "/admin-clinic2",
    # },
}

def get_base_url():
    """Return BASE_URL env var, or fall back to CLINIC_CONFIG site_url."""
    return BASE_URL or CLINIC_CONFIG.get("site_url", "http://localhost:5000").rstrip("/")

# ══════════════════════════════════════════════════════════════════
app = Flask(__name__)

# ── SQLite database ───────────────────────────────────────────────
# Absolute path prevents appointments disappearing when the working
# directory changes (common on Render, Railway, and similar hosts).
# To reset: delete appointments.db — it is recreated on startup.
DB_PATH = os.path.join(os.path.dirname(__file__), "appointments.db")


def cfg(key):
    return CLINIC_CONFIG[key]


def get_db():
    """
    Open and return a fresh SQLite connection.
    Always called per-request — no shared global connection.
    Caller is responsible for calling conn.close().
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row   # rows behave like dicts
    return conn


def init_db():
    """
    Create the appointments table if it does not already exist.
    Called once at startup — safe to run repeatedly (IF NOT EXISTS).
    """
    conn = get_db()
    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS appointments (
                id        TEXT PRIMARY KEY,
                clinic_id TEXT NOT NULL DEFAULT '',
                name      TEXT NOT NULL,
                phone     TEXT NOT NULL,
                date      TEXT NOT NULL,
                time      TEXT NOT NULL,
                problem   TEXT NOT NULL,
                booked_at TEXT NOT NULL
            )
        """)
        conn.commit()
    finally:
        conn.close()


# Create table at startup
init_db()


# ══════════════════════════════════════════════════════════════════
#  DATABASE HELPERS
# ══════════════════════════════════════════════════════════════════

def load_appointments(clinic_id=None):
    """
    Load all appointments from SQLite, always fresh — no caching.
    If clinic_id is given, return only records for that clinic.
    Returns a list of plain dicts (never raises — returns [] on any error).
    """
    try:
        conn = get_db()
        try:
            if clinic_id:
                rows = conn.execute(
                    "SELECT * FROM appointments WHERE clinic_id = ? ORDER BY booked_at DESC",
                    (clinic_id,)
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM appointments ORDER BY booked_at DESC"
                ).fetchall()
            return [dict(r) for r in rows]
        finally:
            conn.close()
    except Exception as exc:
        print(f"[DB] load_appointments error: {exc}")
        return []


def save_appointment(appt):
    """
    Insert a single appointment dict into SQLite.
    Opens connection → inserts → commits → closes.
    Returns True on success, False on any error (never raises).
    """
    try:
        conn = get_db()
        try:
            conn.execute(
                """INSERT INTO appointments
                   (id, clinic_id, name, phone, date, time, problem, booked_at)
                   VALUES (:id, :clinic_id, :name, :phone, :date, :time, :problem, :booked_at)""",
                {
                    "id":        appt["id"],
                    "clinic_id": appt.get("clinic_id", ""),
                    "name":      appt["name"],
                    "phone":     appt["phone"],
                    "date":      appt["date"],
                    "time":      appt["time"],
                    "problem":   appt["problem"],
                    "booked_at": appt["booked_at"],
                }
            )
            conn.commit()
            print(f"[DB] Saved appointment: {appt['name']} on {appt['date']} at {appt['time']}")
            return True
        finally:
            conn.close()
    except sqlite3.IntegrityError:
        # Duplicate id — already saved (idempotent, not an error)
        print(f"[DB] Appointment {appt.get('id')} already exists — skipping duplicate.")
        return True
    except Exception as exc:
        print(f"[DB] save_appointment error: {exc}")
        return False


# ══════════════════════════════════════════════════════════════════
#  TIME SLOT ENGINE
#  Divides clinic_timings into daily_slot_limit equal slots.
#  Auto-assigns the next free slot for a given date.
# ══════════════════════════════════════════════════════════════════

def _parse_clinic_time(raw):
    """Parse "9:00 AM", "9 AM", "18:00" → datetime.time."""
    raw = raw.strip()
    for fmt in ("%I:%M %p", "%I %p", "%H:%M", "%H"):
        try:
            return datetime.strptime(raw.upper(), fmt).time()
        except ValueError:
            pass
    raise ValueError(f"Cannot parse time: {raw!r}")


def generate_time_slots():
    """
    Split clinic_timings into daily_slot_limit equal intervals.
    Returns list of human-readable strings, e.g. ["9:00 AM", "9:54 AM", ...].
    """
    timings = cfg("clinic_timings")
    limit   = cfg("daily_slot_limit")

    # Handle any dash variant as separator
    for sep in [" – ", " - ", "–", "—", "-"]:
        if sep in timings:
            raw_start, raw_end = timings.split(sep, 1)
            break
    else:
        raise ValueError(f"Cannot parse clinic_timings: {timings!r}")

    start = _parse_clinic_time(raw_start)
    end   = _parse_clinic_time(raw_end)

    base       = datetime(2000, 1, 1)
    dt_start   = base.replace(hour=start.hour, minute=start.minute)
    dt_end     = base.replace(hour=end.hour,   minute=end.minute)
    total_mins = int((dt_end - dt_start).total_seconds() / 60)
    interval   = total_mins // limit

    slots = []
    for i in range(limit):
        slot_dt = dt_start + timedelta(minutes=i * interval)
        # Remove leading zero: "09:00 AM" → "9:00 AM"
        slots.append(slot_dt.strftime("%I:%M %p").lstrip("0"))
    return slots


# Generate once at startup
ALL_SLOTS = generate_time_slots()


def get_booked_times(date_str, records=None):
    """Return set of time strings already taken for date_str."""
    if records is None:
        records = load_appointments()
    return {
        r.get("time", "")
        for r in records
        if date_str.lower() in r.get("date", "").lower()
    }


def count_booked(date_str, records=None):
    """Count appointments for date_str."""
    if records is None:
        records = load_appointments()
    return sum(1 for r in records if date_str.lower() in r.get("date", "").lower())


def next_free_slot(date_str, records=None):
    """
    Return the next available (unbooked AND in the future) time slot
    for date_str.

    Rules:
      - A slot is "available" only if it is not already booked.
      - For TODAY: also skip slots whose time has already passed.
        e.g. if current time is 11:30 AM, slots at 9:00 AM and
        10:00 AM are ignored — the next candidate is 12:00 PM or later.
      - For FUTURE dates: time comparison is skipped (all unbooked
        slots are valid).
      - Returns None if no slots remain (caller should suggest next day).
    """
    if records is None:
        records = load_appointments()

    booked     = get_booked_times(date_str, records)
    today_fmt  = format_date(date.today())
    is_today   = (date_str.lower() == today_fmt.lower())
    now        = datetime.now()

    for slot in ALL_SLOTS:
        if slot in booked:
            continue                           # already taken

        if is_today:
            # Parse the slot time and compare against current wall clock
            try:
                slot_t = datetime.strptime(slot, "%I:%M %p")
                slot_dt = now.replace(
                    hour=slot_t.hour, minute=slot_t.minute,
                    second=0, microsecond=0
                )
                if slot_dt <= now:
                    continue                   # this slot is in the past
            except ValueError:
                pass                           # unparseable — include it

        return slot                            # first future unbooked slot

    return None                                # all slots gone


def find_next_open_date(from_date, records=None):
    """
    Walk forward from from_date until a date with free slots is found.
    Searches up to 60 days ahead to avoid infinite loops.
    """
    if records is None:
        records = load_appointments()
    limit = cfg("daily_slot_limit")
    for delta in range(60):
        candidate = from_date + timedelta(days=delta)
        if count_booked(format_date(candidate), records) < limit:
            return candidate
    return from_date + timedelta(days=60)


# ══════════════════════════════════════════════════════════════════
#  DATE HELPERS
# ══════════════════════════════════════════════════════════════════

_MONTHS = {
    "jan":1,"feb":2,"mar":3,"apr":4,"may":5,"jun":6,
    "jul":7,"aug":8,"sep":9,"oct":10,"nov":11,"dec":12,
    "january":1,"february":2,"march":3,"april":4,"june":6,
    "july":7,"august":8,"september":9,"october":10,"november":11,"december":12,
}


def parse_user_date(text):
    """
    Flexible parser: "20 April", "April 20 2026", "2026-04-20", "20/04/2026".
    Returns a date object or None.
    """
    text  = text.strip()
    today = date.today()

    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d-%m-%Y"):
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            pass

    tokens = text.replace(",", " ").split()
    day = month = year = None
    for tok in tokens:
        if tok.isdigit():
            val = int(tok)
            if val > 31:
                year = val
            elif day is None:
                day = val
            else:
                year = val
        else:
            m = _MONTHS.get(tok.lower())
            if m:
                month = m

    if day and month:
        if year is None:
            year = today.year
            try:
                if date(year, month, day) < today:
                    year = today.year + 1
            except ValueError:
                pass
        try:
            return date(year, month, day)
        except ValueError:
            return None
    return None


def format_date(d):
    """date → '04 May 2026'"""
    return d.strftime("%d %B %Y")


def today_str():
    return format_date(date.today())


def example_future_date():
    """Dynamic example, never hardcoded."""
    return format_date(date.today() + timedelta(days=3))


def clinic_end_time():
    """
    Parse the closing time from clinic_timings and return a datetime.time object.
    Returns None if unparseable (so we fail open — allow same-day booking).
    """
    timings = cfg("clinic_timings")
    for sep in [" – ", " - ", "–", "—", "-"]:
        if sep in timings:
            _, raw_end = timings.split(sep, 1)
            try:
                return _parse_clinic_time(raw_end.strip())
            except ValueError:
                return None
    return None


def earliest_bookable_date():
    """
    Return the earliest date a patient can book.

    Rules:
      - Never allow past dates.
      - If today's clinic session has already ended (current time >= closing time),
        today is also blocked → return tomorrow.
      - Otherwise today is still valid → return today.
    """
    today = date.today()
    end   = clinic_end_time()

    if end is not None:
        now_time = datetime.now().time()
        if now_time >= end:
            # Clinic is closed for today — earliest slot is tomorrow
            return today + timedelta(days=1)

    return today


def validate_date(text):
    """
    Parse the user's date input and validate it.

    Rejects:
      - Unparseable input
      - Strictly past dates  (before today)
      - Today when clinic hours are already over

    Returns (date_obj, None) on success, (None, error_message) on failure.
    """
    parsed = parse_user_date(text)
    if parsed is None:
        return None, (
            f"I could not understand that date. "
            f"Please enter a date like: {example_future_date()}"
        )

    earliest = earliest_bookable_date()

    if parsed < earliest:
        if earliest == date.today():
            # Normal past-date rejection
            return None, (
                f"Please select a valid future date. "
                f"Today is {today_str()}."
            )
        else:
            # Clinic hours over for today — steer to tomorrow
            return None, (
                f"Our clinic is closed for today. "
                f"The earliest available date is {format_date(earliest)}.\n"
                f"Please enter {format_date(earliest)} or a later date."
            )

    return parsed, None


# ══════════════════════════════════════════════════════════════════
#  ADMIN DATE FILTERING  (server-side, Python datetime)
# ══════════════════════════════════════════════════════════════════

def filter_appointments(records, period):
    """
    Filter appointments by period.

    period:
      "all"       → all records
      "today"     → appointment date == today
      "yesterday" → appointment date == yesterday
      "last7"     → last 7 days (today inclusive)
      "lastmonth" → previous calendar month
      "lastyear"  → previous calendar year
    """
    if period == "all" or not period:
        return records

    today     = date.today()
    yesterday = today - timedelta(days=1)
    filtered  = []

    for appt in records:
        appt_date = parse_user_date(appt.get("date", ""))
        if appt_date is None:
            continue   # unparseable date — skip in non-"all" views

        if period == "today":
            if appt_date == today:
                filtered.append(appt)

        elif period == "yesterday":
            if appt_date == yesterday:
                filtered.append(appt)

        elif period == "last7":
            if today - timedelta(days=6) <= appt_date <= today:
                filtered.append(appt)

        elif period == "lastmonth":
            first_this = today.replace(day=1)
            last_prev  = first_this - timedelta(days=1)
            first_prev = last_prev.replace(day=1)
            if first_prev <= appt_date <= last_prev:
                filtered.append(appt)

        elif period == "lastyear":
            if appt_date.year == today.year - 1:
                filtered.append(appt)

    return filtered


# ══════════════════════════════════════════════════════════════════
#  TELEGRAM NOTIFICATION
#
#  Called once after a successful appointment save.
#  Each clinic has its own bot_token + chat_id in CLINICS registry.
#  Message: "New Appointment\nCheck Dashboard: <link>"
#  No patient details included. Never raises.
# ══════════════════════════════════════════════════════════════════

def send_telegram_notification(bot_token, chat_id, message):
    """
    Send a Telegram message via the Bot API.
    Uses requests.post() — never raises (errors are printed only).
    """
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    try:
        resp = requests.post(
            url,
            json={"chat_id": chat_id, "text": message},
            timeout=10,
        )
        print(f"[Telegram] Notification sent. Status: {resp.status_code}")
    except Exception as e:
        print("Telegram Error:", e)


# ══════════════════════════════════════════════════════════════════
#  CHAT STATE MACHINE
#  Steps: name → phone → date → problem
#  Time is AUTO-ASSIGNED — patients never manually pick a time.
# ══════════════════════════════════════════════════════════════════

STEPS = ["name", "phone", "date", "problem"]


def build_prompts():
    return {
        "name":    "Please enter your full name.",
        "phone":   "What is your contact phone number?",
        "date":    f"What date would you prefer?\n(e.g. {example_future_date()})",
        "problem": "Please briefly describe your symptoms or reason for the visit.",
    }


FAQ_KEYWORDS = {
    ("timing", "hours", "open", "schedule", "when", "time"):   "timing",
    ("location", "address", "where", "directions", "located"): "location",
    ("fee", "fees", "cost", "charges", "price", "how much"):   "fees",
    ("contact", "reach", "call", "whatsapp", "phone"):         "contact",
}


def faq_answer(topic):
    answers = {
        "timing":   (f"{cfg('clinic_name')} is open {cfg('clinic_days')}, "
                     f"{cfg('clinic_timings')}."),
        "location": f"We are located at {cfg('clinic_location')}.",
        "fees":     (f"The consultation fee is {cfg('clinic_fees')} per visit. "
                     f"We accept cash and all major cards."),
        "contact":  f"Please visit our clinic at {cfg('clinic_location')} during opening hours.",
    }
    return answers.get(topic, "")


# ── Symptom keywords → gentle triage reply ────────────────────────
SYMPTOM_KEYWORDS = (
    "cough", "flu", "fever", "cold", "headache", "pain", "nausea",
    "vomit", "diarrhea", "diarrhoea", "stomach", "throat", "runny",
    "sneeze", "chills", "fatigue", "tired", "sick", "ache", "aches",
)

def detect_symptom(text):
    lower = text.lower()
    return any(kw in lower for kw in SYMPTOM_KEYWORDS)


def match_faq(text):
    lower = text.lower()
    for keywords, topic in FAQ_KEYWORDS.items():
        if any(k in lower for k in keywords):
            return faq_answer(topic)
    return None


def is_book_intent(text):
    return any(k in text.lower() for k in ("book", "appointment", "schedule", "reserve"))


def welcome_text():
    return (
        f"Welcome to {cfg('clinic_name')}.\n"
        f"{cfg('clinic_tagline')}\n\n"
        "I am your appointment assistant. I can help you:\n\n"
        "Book an appointment with our doctor\n"
        f"Check clinic hours ({cfg('clinic_days')}, {cfg('clinic_timings')})\n"
        f"Consultation fee: {cfg('clinic_fees')}\n\n"
        "Use the quick buttons below or type your question."
    )


def idle_help_text():
    return (
        "Here is how I can help:\n\n"
        "Book Appointment — click the button or type 'book'\n"
        f"Hours — {cfg('clinic_days')}, {cfg('clinic_timings')}\n"
        f"Location — {cfg('clinic_location')}\n"
        f"Fees — {cfg('clinic_fees')} per visit"
    )


# ══════════════════════════════════════════════════════════════════
#  MAIN CHAT ENDPOINT
#  Fully wrapped in try/except — NEVER returns a 500 or crashes.
#  Always returns JSON: {"reply": "...", "session": {...}}
# ══════════════════════════════════════════════════════════════════

@app.route("/chat", methods=["POST"])
def chat():
    # Outer safety net — any uncaught exception returns a friendly message
    try:
        body    = request.get_json(silent=True) or {}
        message = (body.get("message") or "").strip()
        session = body.get("session") or {}

        step = session.get("step", "idle")
        data = session.get("data") or {}

        PROMPTS = build_prompts()

        # ── Welcome (first load) ─────────────────────────────────────
        if step == "idle" and message == "":
            try:
                # Read clinic_id from JSON body or URL param.
                # Fall back to "clinic1" so it is NEVER saved as empty string.
                clinic_id = (
                    body.get("clinic_id")
                    or request.args.get("clinic")
                    or "clinic1"
                )
                session.update({"step": "idle", "data": {}, "clinic_id": clinic_id})
                return jsonify(reply=welcome_text(), session=session)
            except Exception as exc:
                print(f"[chat/welcome] {exc}")
                return jsonify(reply=welcome_text(), session=session)

        # ── FAQ button shortcuts (sent as exact keywords by the frontend) ─
        # These are checked before the booking flow so buttons always work
        # regardless of the current session state.
        msg_lower = message.lower().strip()

        # Button: "hours" or "timing" → clinic timing
        if msg_lower in ("hours", "timing", "clinic hours"):
            reply = faq_answer("timing")
            return jsonify(reply=reply, session=session)

        # Button: "fees" → consultation fee
        if msg_lower in ("fees", "fee", "consultation fees"):
            reply = faq_answer("fees")
            return jsonify(reply=reply, session=session)

        # Button: "location" → clinic address
        if msg_lower in ("location", "address"):
            reply = faq_answer("location")
            return jsonify(reply=reply, session=session)

        # ── Symptom detection (checked in idle state only) ────────────
        # If the user types a symptom keyword while not in a booking flow,
        # suggest they see the doctor and offer to book.
        if step == "idle" and detect_symptom(message):
            return jsonify(
                reply=(
                    "It seems like a common issue. "
                    "I recommend consulting the doctor. "
                    "Would you like to book an appointment?"
                ),
                session=session
            )

        # ── Booking flow ──────────────────────────────────────────────
        if step in STEPS:
            try:
                # Phone validation
                if step == "phone" and not any(c.isdigit() for c in message):
                    return jsonify(
                        reply="Please enter a valid phone number (must contain digits).",
                        session=session
                    )

                # ── Date step ─────────────────────────────────────────
                if step == "date":
                    pending = session.get("pending_date")
                    if msg_lower in ("yes", "ok", "sure", "confirm", "okay") and pending:
                        message = pending
                    else:
                        parsed_date, date_error = validate_date(message)
                        if date_error:
                            return jsonify(reply=date_error, session=session)

                        records   = load_appointments()
                        formatted = format_date(parsed_date)

                        if count_booked(formatted, records) >= cfg("daily_slot_limit"):
                            search_from = max(
                                parsed_date + timedelta(days=1),
                                earliest_bookable_date()
                            )
                            next_d     = find_next_open_date(search_from, records)
                            next_d_str = format_date(next_d)
                            new_session = {**session, "pending_date": next_d_str}
                            return jsonify(
                                reply=(
                                    f"The selected date ({formatted}) is fully booked.\n"
                                    f"The next available date is *{next_d_str}*.\n\n"
                                    f"Type 'yes' to confirm {next_d_str}, "
                                    "or enter a different date."
                                ),
                                session=new_session
                            )

                        message = formatted   # normalise to "04 May 2026"

                # Save this step's answer
                data[step]              = message
                session["data"]         = data
                session["pending_date"] = None

                idx = STEPS.index(step)
                if idx + 1 < len(STEPS):
                    next_step = STEPS[idx + 1]
                    session["step"] = next_step

                    if step == "date":
                        records   = load_appointments()
                        remaining = cfg("daily_slot_limit") - count_booked(message, records)
                        note = (f"{remaining} slot{'s' if remaining != 1 else ''} "
                                f"available on this day.\n\n")
                        return jsonify(reply=note + PROMPTS[next_step], session=session)

                    return jsonify(reply=PROMPTS[next_step], session=session)

                # ── All steps complete — assign slot, save, notify ────
                records       = load_appointments()
                assigned_time = next_free_slot(data["date"], records)

                if assigned_time is None:
                    # Today's slots are all either booked or already past.
                    # Automatically move to the next day that has free slots
                    # and assign its first available time — no user restart needed.
                    parsed_appt_date = parse_user_date(data["date"])
                    if parsed_appt_date is None:
                        parsed_appt_date = date.today()

                    next_d        = find_next_open_date(
                        parsed_appt_date + timedelta(days=1), records
                    )
                    next_d_str    = format_date(next_d)
                    assigned_time = next_free_slot(next_d_str, records)

                    if assigned_time is None:
                        # Extremely unlikely — every slot in the next 60 days is booked
                        session.update({"step": "idle", "data": {}})
                        return jsonify(
                            reply=(
                                "No available slots found in the next 60 days. "
                                "Please contact the clinic directly."
                            ),
                            session=session
                        )

                    # Update the booking date to the auto-assigned next day
                    data["date"] = next_d_str

                appt = {
                    **data,                  # includes updated data["date"] if auto-shifted
                    "time":      assigned_time,
                    # Never allow empty clinic_id — fall back to "clinic1"
                    "clinic_id": session.get("clinic_id") or "clinic1",
                    "id":        datetime.now().strftime("%Y%m%d%H%M%S"),
                    "booked_at": datetime.now().isoformat(),
                }

                # Save to SQLite — single insert, no duplicates possible
                saved = save_appointment(appt)

                # Send Telegram notification using the appointment data we have
                # Don't query DB — use the appt object directly (avoids conflicts with other instances)
                if saved:
                    try:
                        cid        = appt.get("clinic_id") or "clinic1"
                        clinic_row = CLINICS.get(cid)

                        if clinic_row:
                            dashboard_url = f"{get_base_url()}{clinic_row['dashboard']}"
                            send_telegram_notification(
                                clinic_row["telegram_bot_token"],
                                clinic_row["telegram_chat_id"],
                                f"New Appointment: {appt['name']}\nCheck Dashboard:\n{dashboard_url}"
                            )
                        else:
                            print(f"[Telegram] Clinic config not found: {cid!r}")

                    except Exception as tg_exc:
                        print("[Telegram] Error:", tg_exc)

                confirmation = (
                    "Appointment Received\n\n"
                    f"Name    : {appt['name']}\n"
                    f"Phone   : {appt['phone']}\n"
                    f"Date    : {appt['date']}\n"
                    f"Time    : {appt['time']}\n"
                    f"Problem : {appt['problem']}\n\n"
                    f"Your appointment has been confirmed for "
                    f"*{appt['date']}* at *{appt['time']}*.\n"
                    "Our team will contact you shortly.\n\n"
                    f"Consultation fee: {cfg('clinic_fees')}\n"
                    "Please arrive 10 minutes before your appointment."
                )

                session.update({"step": "idle", "data": {}})
                return jsonify(
                    reply=confirmation,
                    redirect=f"/receipt?name={appt['name']}&phone={appt['phone']}&date={appt['date']}&time={appt['time']}&problem={appt['problem']}&id={appt['id']}",
                    session=session
                )

            except Exception as exc:
                print(f"[chat/booking-flow] Unhandled error: {exc}")
                session.update({"step": "idle", "data": {}})
                return jsonify(
                    reply="Something went wrong. Please try again or type 'book' to start over.",
                    session=session
                )

        # ── Idle: FAQ text match → book intent → default fallback ────
        try:
            faq = match_faq(message)
            if faq:
                return jsonify(
                    reply=faq + "\n\nType 'book' to schedule an appointment.",
                    session=session
                )

            if is_book_intent(message):
                session.update({"step": "name", "data": {}})
                return jsonify(
                    reply=f"Let us get your appointment scheduled.\n\n{PROMPTS['name']}",
                    session=session
                )

            # Default fallback — always returns something useful
            return jsonify(
                reply=(
                    "How can I help you? "
                    "You can book an appointment or ask about our services.\n\n"
                    + idle_help_text()
                ),
                session=session
            )
        except Exception as exc:
            print(f"[chat/idle] Error: {exc}")
            return jsonify(
                reply="How can I help you? You can book an appointment or ask about services.",
                session=session
            )

    except Exception as critical_exc:
        # Absolute last-resort catch — ensures /chat NEVER returns a 5xx
        print(f"[chat] CRITICAL unhandled exception: {critical_exc}")
        return jsonify(
            reply="How can I help you? You can book an appointment or ask about services.",
            session={}
        )


# ══════════════════════════════════════════════════════════════════
#  PAGE ROUTES
# ══════════════════════════════════════════════════════════════════

@app.route("/")
def index():
    return render_template("index.html", clinic=CLINIC_CONFIG)


@app.route(f"/{CLINIC_CONFIG['admin_path']}")
def admin():
    try:
        period = request.args.get("filter", "all")

        all_records      = load_appointments()          # always fresh from SQLite
        filtered_records = filter_appointments(all_records, period)

        slot_summary = {}
        for appt in all_records:
            d = appt.get("date", "Unknown")
            slot_summary[d] = slot_summary.get(d, 0) + 1

        today_count = len(filter_appointments(all_records, "today"))

        return render_template(
            "admin.html",
            appointments  = filtered_records,
            all_count     = len(all_records),
            today_count   = today_count,
            clinic        = CLINIC_CONFIG,
            slot_summary  = slot_summary,
            active_filter = period,
        )
    except Exception as exc:
        print(f"[admin] Error: {exc}")
        return render_template(
            "admin.html",
            appointments  = [],
            all_count     = 0,
            today_count   = 0,
            clinic        = CLINIC_CONFIG,
            slot_summary  = {},
            active_filter = "all",
        )


@app.route("/api/appointments")
def api_appointments():
    try:
        return jsonify(load_appointments())
    except Exception as exc:
        print(f"[api/appointments] Error: {exc}")
        return jsonify([])


@app.route("/favicon.ico")
def favicon():
    """Suppress 404 errors for browser favicon requests."""
    return "", 204


@app.route("/ping")
def ping():
    """Health-check / uptime-monitor endpoint — keeps Render app warm."""
    return "ok", 200


@app.route("/receipt")
def receipt():
    """Appointment receipt page with download option."""
    try:
        # Get appointment data from URL parameters
        appt_data = {
            "name":     request.args.get("name", ""),
            "phone":    request.args.get("phone", ""),
            "date":     request.args.get("date", ""),
            "time":     request.args.get("time", ""),
            "problem":  request.args.get("problem", ""),
            "id":       request.args.get("id", ""),
        }

        # If no data in URL, show error
        if not any(appt_data.values()):
            return render_template("receipt.html",
                                 appointment=None,
                                 clinic=CLINIC_CONFIG,
                                 error="No appointment data found.")

        return render_template("receipt.html",
                             appointment=appt_data,
                             clinic=CLINIC_CONFIG)

    except Exception as exc:
        print(f"[receipt] Error: {exc}")
        return render_template("receipt.html",
                             appointment=None,
                             clinic=CLINIC_CONFIG,
                             error="Something went wrong loading the receipt.")


@app.route(f"/{CLINIC_CONFIG['admin_path']}/delete/<appt_id>", methods=["POST"])
def delete_appointment(appt_id):
    """Delete a single appointment by ID."""
    try:
        conn = get_db()
        conn.execute("DELETE FROM appointments WHERE id = ?", (appt_id,))
        conn.commit()
        conn.close()
        return redirect(url_for('admin'))
    except Exception as exc:
        print(f"[delete] Error: {exc}")
        return redirect(url_for('admin'))


@app.route(f"/{CLINIC_CONFIG['admin_path']}/delete_all", methods=["POST"])
def delete_all_appointments():
    """Delete all appointments."""
    try:
        conn = get_db()
        conn.execute("DELETE FROM appointments")
        conn.commit()
        conn.close()
        return redirect(url_for('admin'))
    except Exception as exc:
        print(f"[delete_all] Error: {exc}")
        return redirect(url_for('admin'))


# ══════════════════════════════════════════════════════════════════
#  PER-CLINIC ADMIN DASHBOARDS
#  Each clinic in CLINICS gets its own route: /admin-<id>
#  These are generated automatically — no manual route needed when
#  you add a new clinic to the CLINICS dict.
#
#  Each dashboard shows only that clinic's appointments (filtered
#  by clinic_id stored on each appointment at booking time).
# ══════════════════════════════════════════════════════════════════

def _make_clinic_admin(cid):
    """
    Factory that returns a view function for a given clinic_id.
    We use a factory so the closure captures cid correctly in a loop.
    """
    def clinic_admin_view():
        try:
            period      = request.args.get("filter", "all")
            clinic_info = CLINICS[cid]

            # Load only this clinic's records — SQLite filters by clinic_id
            all_records      = load_appointments(clinic_id=cid)
            filtered_records = filter_appointments(all_records, period)

            slot_summary = {}
            for appt in all_records:
                d = appt.get("date", "Unknown")
                slot_summary[d] = slot_summary.get(d, 0) + 1

            today_count = len(filter_appointments(all_records, "today"))

            clinic_ctx = {
                **CLINIC_CONFIG,
                "clinic_name":  clinic_info["name"],
                "admin_path":   clinic_info["dashboard"].lstrip("/"),
            }

            return render_template(
                "admin.html",
                appointments  = filtered_records,
                all_count     = len(all_records),
                today_count   = today_count,
                clinic        = clinic_ctx,
                slot_summary  = slot_summary,
                active_filter = period,
            )
        except Exception as exc:
            print(f"[clinic_admin/{cid}] Error: {exc}")
            clinic_info = CLINICS.get(cid, {})
            clinic_ctx  = {**CLINIC_CONFIG, "clinic_name": clinic_info.get("name", cid),
                           "admin_path": clinic_info.get("dashboard", "").lstrip("/")}
            return render_template(
                "admin.html",
                appointments=[], all_count=0, today_count=0,
                clinic=clinic_ctx, slot_summary={}, active_filter="all",
            )

    clinic_admin_view.__name__ = f"clinic_admin_{cid}"
    return clinic_admin_view


# Register one route per clinic  (e.g. /admin-abc, /admin-xyz)
for _cid, _clinic_data in CLINICS.items():
    _path = _clinic_data["dashboard"]          # e.g. "/admin-abc"
    app.add_url_rule(_path, endpoint=f"clinic_admin_{_cid}",
                     view_func=_make_clinic_admin(_cid))


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)