"""
╔══════════════════════════════════════════════════════════════════╗
║         CLINIC APPOINTMENT CHATBOT  —  Flask Backend            ║
║         Reusable · Multi-client · International-ready           ║
╠══════════════════════════════════════════════════════════════════╣
║  HOW TO CUSTOMISE FOR A NEW CLIENT:                             ║
║    1.  Edit CLINIC_CONFIG below — nothing else needs changing.  ║
║    2.  Set Meta WhatsApp env vars for notifications.            ║
║    3.  To reset appointment data: empty appointments.json       ║
║        or delete the file — it is recreated automatically.      ║
║                                                                 ║
║  MULTI-CLIENT SAFETY:                                           ║
║    Keep each client in a separate project folder.               ║
║    Never share the same appointments.json across clients.       ║
╚══════════════════════════════════════════════════════════════════╝
"""

from flask import Flask, request, jsonify, render_template, make_response
import json, os
from datetime import datetime, date, timedelta
import urllib.request, urllib.error

# ══════════════════════════════════════════════════════════════════
#  CLINIC CONFIGURATION  ←  Edit this section only
# ══════════════════════════════════════════════════════════════════
CLINIC_CONFIG = {
    # Identity
    "clinic_name":            "CarePlus Clinic",
    "clinic_tagline":         "Trusted care, every visit",

    # Contact & location
    "clinic_location":        "London, UK",

    # Hours — used to auto-generate time slots
    # Format: "H:MM AM – H:MM PM"  or  "H AM – H PM"
    "clinic_timings":         "9:00 AM – 6:00 PM",
    "clinic_days":            "Monday to Saturday",

    # Fees (shown exactly as written — supports any currency)
    "clinic_fees":            "$20",

    # UI theme (any valid CSS colour)
    "primary_color":          "#2563eb",

    # Slot control — max appointments per calendar day
    # Time slots are auto-generated by dividing clinic hours by this number
    "daily_slot_limit":       10,

    # Hidden admin path — change this, share only with clinic owner
    "admin_path":             "admin-unique123",

    # Your deployed domain (no trailing slash)
    # Local:      http://localhost:5000
    # Production: https://yourclinic.com
    "site_url":               "http://localhost:5000",
}

# ── Meta WhatsApp Business API credentials ───────────────────────
# Set these environment variables on your server. Never hardcode.
#
#   META_TOKEN               — your permanent access token from Meta developer console
#   META_PHONE_ID            — Phone Number ID from WhatsApp Business API settings
#   DOCTOR_WHATSAPP_NUMBER   — doctor's WhatsApp number in E.164, e.g. +923001234567
#   META_VERIFY_TOKEN        — any secret string you choose for webhook verification
#   BASE_URL                 — public domain, e.g. https://yourclinic.com (no trailing slash)
#
META_TOKEN             = os.environ.get("META_TOKEN", "")
META_PHONE_ID          = os.environ.get("META_PHONE_ID", "")
DOCTOR_WHATSAPP_NUMBER = os.environ.get("DOCTOR_WHATSAPP_NUMBER", "")
META_VERIFY_TOKEN      = os.environ.get("META_VERIFY_TOKEN", "my_verify_token")
BASE_URL               = os.environ.get("BASE_URL", "").rstrip("/")

# ══════════════════════════════════════════════════════════════════
#  MULTI-CLINIC REGISTRY
#  Add one entry per clinic. clinic_id must match the ?clinic= param
#  used in booking links and the WhatsApp webhook.
#
#  doctor_number : E.164, no "whatsapp:" prefix (added automatically)
#  dashboard     : URL path for that clinic's admin page
# ══════════════════════════════════════════════════════════════════
CLINICS = {
    "abc": {
        "name":           "ABC Clinic",
        "doctor_number":  "+123456789",     # ← replace with real number
        "dashboard":      "/admin-abc",
    },
    "xyz": {
        "name":           "XYZ Clinic",
        "doctor_number":  "+987654321",     # ← replace with real number
        "dashboard":      "/admin-xyz",
    },
}

def get_base_url():
    """Return BASE_URL env var, or fall back to CLINIC_CONFIG site_url."""
    return BASE_URL or CLINIC_CONFIG.get("site_url", "http://localhost:5000").rstrip("/")

# ══════════════════════════════════════════════════════════════════
app     = Flask(__name__)

# ── Appointments file ─────────────────────────────────────────────
# To reset: replace file contents with []  or just delete the file.
DB_FILE = "appointments.json"


def cfg(key):
    return CLINIC_CONFIG[key]


# ══════════════════════════════════════════════════════════════════
#  DATABASE HELPERS
# ══════════════════════════════════════════════════════════════════

def load_appointments():
    """
    Always read fresh from disk.
    Returns an empty list if the file does not exist or is empty/corrupt.
    No in-memory caching — every call gets the latest data.
    """
    if not os.path.exists(DB_FILE):
        return []
    try:
        with open(DB_FILE, "r", encoding="utf-8") as f:
            content = f.read().strip()
        if not content:
            return []
        data = json.loads(content)
        # Guard against corrupt file containing a non-list
        return data if isinstance(data, list) else []
    except (json.JSONDecodeError, OSError):
        return []


def save_appointments(records):
    """
    Atomically write the appointments list to disk.

    Uses a temp file + rename (atomic on POSIX) so a crash mid-write
    never leaves the file in a corrupt/partial state, which would cause
    ghost or duplicate appointments to appear on the dashboard.
    """
    tmp = DB_FILE + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2, ensure_ascii=False)
    os.replace(tmp, DB_FILE)   # atomic on Linux/Mac; near-atomic on Windows


# ══════════════════════════════════════════════════════════════════
#  TIME SLOT ENGINE
#  Divides clinic_timings into daily_slot_limit equal slots.
#  Auto-assigns the next free slot for a given date.
# ══════════════════════════════════════════════════════════════════

def _parse_clinic_time(raw):
    """Parse "9:00 AM", "9 AM", "18:00" → datetime.time."""
    raw = raw.strip()
    for fmt in ("%I:%M %p", "%I %p", "%H:%M", "%H"):
        try:
            return datetime.strptime(raw.upper(), fmt).time()
        except ValueError:
            pass
    raise ValueError(f"Cannot parse time: {raw!r}")


def generate_time_slots():
    """
    Split clinic_timings into daily_slot_limit equal intervals.
    Returns list of human-readable strings, e.g. ["9:00 AM", "9:54 AM", ...].
    """
    timings = cfg("clinic_timings")
    limit   = cfg("daily_slot_limit")

    # Handle any dash variant as separator
    for sep in [" – ", " - ", "–", "—", "-"]:
        if sep in timings:
            raw_start, raw_end = timings.split(sep, 1)
            break
    else:
        raise ValueError(f"Cannot parse clinic_timings: {timings!r}")

    start = _parse_clinic_time(raw_start)
    end   = _parse_clinic_time(raw_end)

    base       = datetime(2000, 1, 1)
    dt_start   = base.replace(hour=start.hour, minute=start.minute)
    dt_end     = base.replace(hour=end.hour,   minute=end.minute)
    total_mins = int((dt_end - dt_start).total_seconds() / 60)
    interval   = total_mins // limit

    slots = []
    for i in range(limit):
        slot_dt = dt_start + timedelta(minutes=i * interval)
        # Remove leading zero: "09:00 AM" → "9:00 AM"
        slots.append(slot_dt.strftime("%I:%M %p").lstrip("0"))
    return slots


# Generate once at startup
ALL_SLOTS = generate_time_slots()


def get_booked_times(date_str, records=None):
    """Return set of time strings already taken for date_str."""
    if records is None:
        records = load_appointments()
    return {
        r.get("time", "")
        for r in records
        if date_str.lower() in r.get("date", "").lower()
    }


def count_booked(date_str, records=None):
    """Count appointments for date_str."""
    if records is None:
        records = load_appointments()
    return sum(1 for r in records if date_str.lower() in r.get("date", "").lower())


def next_free_slot(date_str, records=None):
    """Return the next unbooked slot string, or None if all full."""
    if records is None:
        records = load_appointments()
    booked = get_booked_times(date_str, records)
    for slot in ALL_SLOTS:
        if slot not in booked:
            return slot
    return None


def find_next_open_date(from_date, records=None):
    """
    Walk forward from from_date until a date with free slots is found.
    Searches up to 60 days ahead to avoid infinite loops.
    """
    if records is None:
        records = load_appointments()
    limit = cfg("daily_slot_limit")
    for delta in range(60):
        candidate = from_date + timedelta(days=delta)
        if count_booked(format_date(candidate), records) < limit:
            return candidate
    return from_date + timedelta(days=60)


# ══════════════════════════════════════════════════════════════════
#  DATE HELPERS
# ══════════════════════════════════════════════════════════════════

_MONTHS = {
    "jan":1,"feb":2,"mar":3,"apr":4,"may":5,"jun":6,
    "jul":7,"aug":8,"sep":9,"oct":10,"nov":11,"dec":12,
    "january":1,"february":2,"march":3,"april":4,"june":6,
    "july":7,"august":8,"september":9,"october":10,"november":11,"december":12,
}


def parse_user_date(text):
    """
    Flexible parser: "20 April", "April 20 2026", "2026-04-20", "20/04/2026".
    Returns a date object or None.
    """
    text  = text.strip()
    today = date.today()

    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d-%m-%Y"):
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            pass

    tokens = text.replace(",", " ").split()
    day = month = year = None
    for tok in tokens:
        if tok.isdigit():
            val = int(tok)
            if val > 31:
                year = val
            elif day is None:
                day = val
            else:
                year = val
        else:
            m = _MONTHS.get(tok.lower())
            if m:
                month = m

    if day and month:
        if year is None:
            year = today.year
            try:
                if date(year, month, day) < today:
                    year = today.year + 1
            except ValueError:
                pass
        try:
            return date(year, month, day)
        except ValueError:
            return None
    return None


def format_date(d):
    """date → '04 May 2026'"""
    return d.strftime("%d %B %Y")


def today_str():
    return format_date(date.today())


def example_future_date():
    """Dynamic example, never hardcoded."""
    return format_date(date.today() + timedelta(days=3))


def clinic_end_time():
    """
    Parse the closing time from clinic_timings and return a datetime.time object.
    Returns None if unparseable (so we fail open — allow same-day booking).
    """
    timings = cfg("clinic_timings")
    for sep in [" – ", " - ", "–", "—", "-"]:
        if sep in timings:
            _, raw_end = timings.split(sep, 1)
            try:
                return _parse_clinic_time(raw_end.strip())
            except ValueError:
                return None
    return None


def earliest_bookable_date():
    """
    Return the earliest date a patient can book.

    Rules:
      - Never allow past dates.
      - If today's clinic session has already ended (current time >= closing time),
        today is also blocked → return tomorrow.
      - Otherwise today is still valid → return today.
    """
    today = date.today()
    end   = clinic_end_time()

    if end is not None:
        now_time = datetime.now().time()
        if now_time >= end:
            # Clinic is closed for today — earliest slot is tomorrow
            return today + timedelta(days=1)

    return today


def validate_date(text):
    """
    Parse the user's date input and validate it.

    Rejects:
      - Unparseable input
      - Strictly past dates  (before today)
      - Today when clinic hours are already over

    Returns (date_obj, None) on success, (None, error_message) on failure.
    """
    parsed = parse_user_date(text)
    if parsed is None:
        return None, (
            f"I could not understand that date. "
            f"Please enter a date like: {example_future_date()}"
        )

    earliest = earliest_bookable_date()

    if parsed < earliest:
        if earliest == date.today():
            # Normal past-date rejection
            return None, (
                f"Please select a valid future date. "
                f"Today is {today_str()}."
            )
        else:
            # Clinic hours over for today — steer to tomorrow
            return None, (
                f"Our clinic is closed for today. "
                f"The earliest available date is {format_date(earliest)}.\n"
                f"Please enter {format_date(earliest)} or a later date."
            )

    return parsed, None


# ══════════════════════════════════════════════════════════════════
#  ADMIN DATE FILTERING  (server-side, Python datetime)
# ══════════════════════════════════════════════════════════════════

def filter_appointments(records, period):
    """
    Filter appointments by period.

    period:
      "all"       → all records
      "today"     → appointment date == today
      "yesterday" → appointment date == yesterday
      "last7"     → last 7 days (today inclusive)
      "lastmonth" → previous calendar month
      "lastyear"  → previous calendar year
    """
    if period == "all" or not period:
        return records

    today     = date.today()
    yesterday = today - timedelta(days=1)
    filtered  = []

    for appt in records:
        appt_date = parse_user_date(appt.get("date", ""))
        if appt_date is None:
            continue   # unparseable date — skip in non-"all" views

        if period == "today":
            if appt_date == today:
                filtered.append(appt)

        elif period == "yesterday":
            if appt_date == yesterday:
                filtered.append(appt)

        elif period == "last7":
            if today - timedelta(days=6) <= appt_date <= today:
                filtered.append(appt)

        elif period == "lastmonth":
            first_this = today.replace(day=1)
            last_prev  = first_this - timedelta(days=1)
            first_prev = last_prev.replace(day=1)
            if first_prev <= appt_date <= last_prev:
                filtered.append(appt)

        elif period == "lastyear":
            if appt_date.year == today.year - 1:
                filtered.append(appt)

    return filtered


# ══════════════════════════════════════════════════════════════════
#  WHATSAPP NOTIFICATION  —  Meta WhatsApp Business API
#
#  Called once after an appointment is saved.
#  Sends only:  "New Appointment\nCheck Dashboard: <link>"
#  No patient details are included.
#
#  Uses urllib (stdlib) — no extra pip install required.
#  Requires META_TOKEN, META_PHONE_ID, DOCTOR_WHATSAPP_NUMBER env vars.
# ══════════════════════════════════════════════════════════════════

def send_whatsapp_notification(appt):
    """
    Send a minimal WhatsApp notification to the clinic doctor via
    the Meta WhatsApp Business API.

    Message format (as requested):
        New Appointment
        Check Dashboard: https://your-domain.com/admin-abc
    """
    if not (META_TOKEN and META_PHONE_ID and DOCTOR_WHATSAPP_NUMBER):
        print("[WhatsApp] Meta credentials not set — notification skipped.")
        print("  Set META_TOKEN, META_PHONE_ID, DOCTOR_WHATSAPP_NUMBER env vars.")
        return False

    try:
        base = get_base_url()

        # Resolve dashboard link from CLINICS or fall back to CLINIC_CONFIG
        clinic_id = appt.get("clinic_id", "")
        clinic    = CLINICS.get(clinic_id) if clinic_id else None
        if clinic:
            dashboard_url = f"{base}{clinic['dashboard']}"
        else:
            dashboard_url = f"{base}/{cfg('admin_path')}"

        message_body = (
            "New Appointment\n"
            f"Check Dashboard: {dashboard_url}"
        )

        # Build the Meta Cloud API request
        api_url = f"https://graph.facebook.com/v19.0/{META_PHONE_ID}/messages"

        payload = json.dumps({
            "messaging_product": "whatsapp",
            "to":                DOCTOR_WHATSAPP_NUMBER,
            "type":              "text",
            "text":              {"body": message_body},
        }).encode("utf-8")

        req = urllib.request.Request(
            api_url,
            data    = payload,
            method  = "POST",
            headers = {
                "Authorization": f"Bearer {META_TOKEN}",
                "Content-Type":  "application/json",
            },
        )

        with urllib.request.urlopen(req, timeout=10) as resp:
            status = resp.status
            print(f"[WhatsApp] Notification sent. Status: {status}")
            print(f"[WhatsApp] Dashboard: {dashboard_url}")
            return True

    except urllib.error.HTTPError as exc:
        print(f"[WhatsApp] HTTP error {exc.code}: {exc.read().decode()}")
        return False
    except Exception as exc:
        print(f"[WhatsApp] Error: {exc}")
        return False


# ══════════════════════════════════════════════════════════════════
#  CHAT STATE MACHINE
#  Steps: name → phone → date → problem
#  Time is AUTO-ASSIGNED — patients never manually pick a time.
# ══════════════════════════════════════════════════════════════════

STEPS = ["name", "phone", "date", "problem"]


def build_prompts():
    return {
        "name":    "Please enter your full name.",
        "phone":   "What is your contact phone number?",
        "date":    f"What date would you prefer?\n(e.g. {example_future_date()})",
        "problem": "Please briefly describe your symptoms or reason for the visit.",
    }


FAQ_KEYWORDS = {
    ("timing", "hours", "open", "schedule", "when", "time"):   "timing",
    ("location", "address", "where", "directions", "located"): "location",
    ("fee", "fees", "cost", "charges", "price", "how much"):   "fees",
    ("contact", "reach", "call", "whatsapp", "phone"):         "contact",
}


def faq_answer(topic):
    return {
        "timing":   (f"{cfg('clinic_name')} is open {cfg('clinic_days')}, "
                     f"{cfg('clinic_timings')}."),
        "location": f"We are located at {cfg('clinic_location')}.",
        "fees":     (f"The consultation fee is {cfg('clinic_fees')} per visit. "
                     f"We accept cash and all major cards."),
        "contact":  (f"You can reach us via WhatsApp at "
                     f"{cfg('clinic_whatsapp_number').replace('whatsapp:', '')}."),
    }[topic]


def match_faq(text):
    lower = text.lower()
    for keywords, topic in FAQ_KEYWORDS.items():
        if any(k in lower for k in keywords):
            return faq_answer(topic)
    return None


def is_book_intent(text):
    return any(k in text.lower() for k in ("book", "appointment", "schedule", "reserve"))


def welcome_text():
    return (
        f"Welcome to {cfg('clinic_name')}.\n"
        f"{cfg('clinic_tagline')}\n\n"
        "I am your appointment assistant. I can help you:\n\n"
        "Book an appointment with our doctor\n"
        f"Check clinic hours ({cfg('clinic_days')}, {cfg('clinic_timings')})\n"
        f"Consultation fee: {cfg('clinic_fees')}\n\n"
        "Use the quick buttons below or type your question."
    )


def idle_help_text():
    return (
        "Here is how I can help:\n\n"
        "Book Appointment — click the button or type 'book'\n"
        f"Hours — {cfg('clinic_days')}, {cfg('clinic_timings')}\n"
        f"Location — {cfg('clinic_location')}\n"
        f"Fees — {cfg('clinic_fees')} per visit"
    )


# ══════════════════════════════════════════════════════════════════
#  MAIN CHAT ENDPOINT
# ══════════════════════════════════════════════════════════════════

@app.route("/chat", methods=["POST"])
def chat():
    body    = request.json or {}
    message = body.get("message", "").strip()
    session = body.get("session", {})

    step = session.get("step", "idle")
    data = session.get("data", {})

    PROMPTS = build_prompts()

    # ── Welcome ───────────────────────────────────────────────────
    if step == "idle" and message == "":
        # Capture clinic_id from URL query param (?clinic=abc) and keep in session.
        # This is passed back by the frontend in subsequent requests so we know
        # which clinic this appointment belongs to.
        clinic_id = request.json.get("clinic_id", "") or request.args.get("clinic", "")
        session.update({"step": "idle", "data": {}, "clinic_id": clinic_id})
        return jsonify(reply=welcome_text(), session=session)

    # ── Booking flow ──────────────────────────────────────────────
    if step in STEPS:

        # Phone validation
        if step == "phone" and not any(c.isdigit() for c in message):
            return jsonify(
                reply="Please enter a valid phone number (must contain digits).",
                session=session
            )

        # ── Date step ──────────────────────────────────────────────
        if step == "date":
            # Allow patient to confirm an auto-suggested date
            pending = session.get("pending_date")
            if message.lower().strip() in ("yes", "ok", "sure", "confirm", "okay") and pending:
                message = pending
            else:
                # Parse and validate the date (rejects past + clinic-closed-today)
                parsed_date, date_error = validate_date(message)
                if date_error:
                    return jsonify(reply=date_error, session=session)

                records   = load_appointments()
                formatted = format_date(parsed_date)

                # Date is full — find and suggest next open date
                if count_booked(formatted, records) >= cfg("daily_slot_limit"):
                    # Start search from the day after the rejected date,
                    # but never before the earliest bookable date
                    search_from = max(
                        parsed_date + timedelta(days=1),
                        earliest_bookable_date()
                    )
                    next_d     = find_next_open_date(search_from, records)
                    next_d_str = format_date(next_d)
                    new_session = {**session, "pending_date": next_d_str}
                    return jsonify(
                        reply=(
                            f"The selected date ({formatted}) is fully booked.\n"
                            f"The next available date is *{next_d_str}*.\n\n"
                            f"Type 'yes' to confirm {next_d_str}, "
                            "or enter a different date."
                        ),
                        session=new_session
                    )

                message = formatted  # normalise to "04 May 2026"

        # Save the answer for this step
        data[step] = message
        session["data"]         = data
        session["pending_date"] = None   # clear any pending suggestion

        idx = STEPS.index(step)
        if idx + 1 < len(STEPS):
            next_step = STEPS[idx + 1]
            session["step"] = next_step

            # After date confirmed: show slots remaining
            if step == "date":
                records   = load_appointments()
                remaining = cfg("daily_slot_limit") - count_booked(message, records)
                note = (f"{remaining} slot{'s' if remaining != 1 else ''} "
                        f"available on this day.\n\n")
                return jsonify(reply=note + PROMPTS[next_step], session=session)

            return jsonify(reply=PROMPTS[next_step], session=session)

        # ── All steps done — auto-assign time, save, confirm ───────
        records       = load_appointments()
        assigned_time = next_free_slot(data["date"], records)

        if assigned_time is None:
            # Edge case: date filled between steps
            next_d = find_next_open_date(
                parse_user_date(data["date"]) + timedelta(days=1), records
            )
            session.update({"step": "idle", "data": {}})
            return jsonify(
                reply=(
                    f"That date just filled up. "
                    f"Please book again and select {format_date(next_d)} instead."
                ),
                session=session
            )

        appt = {
            **data,
            "time":      assigned_time,
            "clinic_id": session.get("clinic_id", ""),   # set by chat endpoint from ?clinic= param
            "id":        datetime.now().strftime("%Y%m%d%H%M%S"),
            "booked_at": datetime.now().isoformat(),
        }
        records.append(appt)
        save_appointments(records)
        send_whatsapp_notification(appt)

        confirmation = (
            "Appointment Received\n\n"
            f"Name    : {appt['name']}\n"
            f"Phone   : {appt['phone']}\n"
            f"Date    : {appt['date']}\n"
            f"Time    : {appt['time']}\n"
            f"Problem : {appt['problem']}\n\n"
            f"Your appointment request has been received for "
            f"*{appt['date']}* at *{appt['time']}*.\n"
            "Our team will contact you shortly.\n\n"
            f"Consultation fee: {cfg('clinic_fees')}\n"
            "Please arrive 10 minutes before your appointment."
        )

        session.update({"step": "idle", "data": {}})
        return jsonify(reply=confirmation, session=session)

    # ── Idle: FAQ → book intent → fallback ───────────────────────
    faq = match_faq(message)
    if faq:
        return jsonify(
            reply=faq + "\n\nType 'book' to schedule an appointment.",
            session=session
        )

    if is_book_intent(message):
        session.update({"step": "name", "data": {}})
        return jsonify(
            reply=f"Let us get your appointment scheduled.\n\n{PROMPTS['name']}",
            session=session
        )

    return jsonify(reply=idle_help_text(), session=session)


# ══════════════════════════════════════════════════════════════════
#  PAGE ROUTES
# ══════════════════════════════════════════════════════════════════

@app.route("/")
def index():
    return render_template("index.html", clinic=CLINIC_CONFIG)


@app.route(f"/{CLINIC_CONFIG['admin_path']}")
def admin():
    # Read filter from ?filter=today etc.
    period = request.args.get("filter", "all")

    all_records      = load_appointments()
    filtered_records = filter_appointments(all_records, period)

    # Slot summary always uses ALL records (so bars stay accurate)
    slot_summary = {}
    for appt in all_records:
        d = appt.get("date", "Unknown")
        slot_summary[d] = slot_summary.get(d, 0) + 1

    today_count = len(filter_appointments(all_records, "today"))

    return render_template(
        "admin.html",
        appointments  = filtered_records,
        all_count     = len(all_records),
        today_count   = today_count,
        clinic        = CLINIC_CONFIG,
        slot_summary  = slot_summary,
        active_filter = period,
    )


@app.route("/api/appointments")
def api_appointments():
    return jsonify(load_appointments())


# ══════════════════════════════════════════════════════════════════
#  WHATSAPP WEBHOOK  —  Meta WhatsApp Business API
#
#  SET UP in Meta Developer Console:
#    App → WhatsApp → Configuration → Webhook
#    Callback URL : https://your-domain.com/whatsapp
#    Verify Token : value of META_VERIFY_TOKEN env var
#    Subscribe to : messages
#
#  GET  /whatsapp  — Meta verification handshake (one-time setup)
#  POST /whatsapp  — receives incoming patient messages
#
#  Reply format (sent back via Meta Cloud API):
#    "Welcome to <Clinic Name> 👋
#     📅 Book Appointment:
#     <booking link>
#     💬 You can also ask your questions here"
# ══════════════════════════════════════════════════════════════════

@app.route("/whatsapp", methods=["GET"])
def whatsapp_verify():
    """
    Meta webhook verification handshake.
    Meta sends a GET with hub.challenge — we echo it back if the
    verify token matches META_VERIFY_TOKEN.
    """
    mode      = request.args.get("hub.mode")
    token     = request.args.get("hub.verify_token")
    challenge = request.args.get("hub.challenge")

    if mode == "subscribe" and token == META_VERIFY_TOKEN:
        print("[WhatsApp] Webhook verified by Meta.")
        return challenge, 200
    return "Verification failed", 403


@app.route("/whatsapp", methods=["POST"])
def whatsapp_webhook():
    """
    Receive incoming WhatsApp messages from patients via Meta API.
    Reply with a welcome message containing the booking link.

    The clinic is identified by ?clinic=<id> appended to the webhook
    URL (configure per clinic in the Meta dashboard).
    """
    data = request.get_json(silent=True) or {}

    # Extract the sender's phone number from the Meta payload
    try:
        entry   = data["entry"][0]
        change  = entry["changes"][0]
        value   = change["value"]
        message = value["messages"][0]
        sender  = message["from"]                   # patient's phone number
    except (KeyError, IndexError):
        # Not a message event (e.g. status update) — acknowledge and ignore
        return jsonify({"status": "ok"}), 200

    # Resolve clinic from ?clinic= query param
    clinic_id  = request.args.get("clinic", "")
    clinic_row = CLINICS.get(clinic_id)
    base       = get_base_url()

    if clinic_row:
        clinic_name  = clinic_row["name"]
        booking_link = f"{base}/?clinic={clinic_id}"
    else:
        clinic_name  = cfg("clinic_name")
        booking_link = f"{base}/"

    reply_text = (
        f"Welcome to {clinic_name} 👋\n\n"
        f"📅 Book Appointment:\n"
        f"{booking_link}\n\n"
        f"💬 You can also ask your questions here"
    )

    # Send the reply via Meta Cloud API
    if META_TOKEN and META_PHONE_ID:
        try:
            api_url = f"https://graph.facebook.com/v19.0/{META_PHONE_ID}/messages"
            payload = json.dumps({
                "messaging_product": "whatsapp",
                "to":                sender,
                "type":              "text",
                "text":              {"body": reply_text},
            }).encode("utf-8")

            req = urllib.request.Request(
                api_url,
                data    = payload,
                method  = "POST",
                headers = {
                    "Authorization": f"Bearer {META_TOKEN}",
                    "Content-Type":  "application/json",
                },
            )
            urllib.request.urlopen(req, timeout=10)
            print(f"[WhatsApp] Welcome reply sent to {sender}")
        except Exception as exc:
            print(f"[WhatsApp] Reply error: {exc}")
    else:
        print(f"[WhatsApp] Meta creds not set — would reply to {sender}: {reply_text}")

    # Always return 200 to Meta to acknowledge receipt
    return jsonify({"status": "ok"}), 200


# ══════════════════════════════════════════════════════════════════
#  PER-CLINIC ADMIN DASHBOARDS
#  Each clinic in CLINICS gets its own route: /admin-<id>
#  These are generated automatically — no manual route needed when
#  you add a new clinic to the CLINICS dict.
#
#  Each dashboard shows only that clinic's appointments (filtered
#  by clinic_id stored on each appointment at booking time).
# ══════════════════════════════════════════════════════════════════

def _make_clinic_admin(cid):
    """
    Factory that returns a view function for a given clinic_id.
    We use a factory so the closure captures cid correctly in a loop.
    """
    def clinic_admin_view():
        period      = request.args.get("filter", "all")
        clinic_info = CLINICS[cid]

        # Load only this clinic's appointments
        all_records = [
            a for a in load_appointments()
            if a.get("clinic_id") == cid
        ]
        filtered_records = filter_appointments(all_records, period)

        slot_summary = {}
        for appt in all_records:
            d = appt.get("date", "Unknown")
            slot_summary[d] = slot_summary.get(d, 0) + 1

        today_count = len(filter_appointments(all_records, "today"))

        # Build a minimal CLINIC_CONFIG-compatible dict for the template
        clinic_ctx = {
            **CLINIC_CONFIG,                          # keep colours/timings/fees
            "clinic_name":  clinic_info["name"],
            "admin_path":   clinic_info["dashboard"].lstrip("/"),
        }

        return render_template(
            "admin.html",
            appointments  = filtered_records,
            all_count     = len(all_records),
            today_count   = today_count,
            clinic        = clinic_ctx,
            slot_summary  = slot_summary,
            active_filter = period,
        )

    # Flask requires unique endpoint names
    clinic_admin_view.__name__ = f"clinic_admin_{cid}"
    return clinic_admin_view


# Register one route per clinic  (e.g. /admin-abc, /admin-xyz)
for _cid, _clinic_data in CLINICS.items():
    _path = _clinic_data["dashboard"]          # e.g. "/admin-abc"
    app.add_url_rule(_path, endpoint=f"clinic_admin_{_cid}",
                     view_func=_make_clinic_admin(_cid))


if __name__ == "__main__":
    app.run(port=5000)